import '../../model/member_list/member_list_model.dart';
import 'member_list_api_repository.dart';

/// Mock implementation of [MemberApiRepository] for simulating fetching member list.
class MemberMockApiRepository implements MemberApiRepository {
  @override
  Future<MemberListModel> fetchMemberList() async {
    // Simulate a delay to mimic network latency
    await Future.delayed(const Duration(seconds: 2));
    // Mock response data
    dynamic responseData = {
      "status": true,
      "data": [
        {
          "member_id": "2",
          "primary_member": "yes",
          "under_id": "0",
          "relative_id": "730419",
          "relation": "",
          "name": "John Due",
          "moblie_no": "7412589632",
          "email": "aansari81786@gmail.com",
          "profession": "Devlaper",
          "age": "25",
          "d_o_b": "2025-07-12",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/profile.png",
          "address": "A/112 Panorama Complex, R C Dutt Road, R C Dutt Road",
          "created_at": "2025-07-12 10:49:00",
          "status": "1",
        },
        {
          "member_id": "3",
          "primary_member": "no",
          "under_id": "2",
          "relative_id": "2",
          "relation": "Sun",
          "name": "Ram",
          "moblie_no": "7896541236",
          "email": "ram@gmail.com",
          "profession": "Devlaper",
          "age": "30",
          "d_o_b": "2025-07-12",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/profile.png",
          "address": "112, Doshi Chamber, Poona Sholapur Street Cor, Masjid Bunder (east)",
          "created_at": "2025-07-12 11:42:35",
          "status": "1",
        },
        {
          "member_id": "4",
          "primary_member": "no",
          "under_id": "2",
          "relative_id": "730419",
          "relation": "Daughter",
          "name": "Raviya",
          "moblie_no": "7412589326",
          "email": "rabi@gmail.com",
          "profession": "Enginear",
          "age": "26",
          "d_o_b": "2025-07-05",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/1.png",
          "address": "Ernest Borges Road, Parel",
          "created_at": "2025-07-14 06:36:01",
          "status": "1",
        },
        {
          "member_id": "5",
          "primary_member": "no",
          "under_id": "2",
          "relative_id": "730419",
          "relation": "Sun",
          "name": "Roy",
          "moblie_no": "7854965896",
          "email": "roy@gmail.com",
          "profession": "Docter",
          "age": "30",
          "d_o_b": "2025-07-01",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/3.png",
          "address": "10-2-317/23/1, V.n.colony",
          "created_at": "2025-07-14 06:39:11",
          "status": "1",
        },
        {
          "member_id": "8",
          "primary_member": "no",
          "under_id": "3",
          "relative_id": "730419",
          "relation": "Sun",
          "name": "Ramgopal",
          "moblie_no": "8569856989",
          "email": "ramgopal@gmail.com",
          "profession": "Docter",
          "age": "22",
          "d_o_b": "2000-06-20",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/3.png",
          "address": "Nr Maninagar Police Station, Maninagar",
          "created_at": "2025-07-14 08:02:37",
          "status": "1",
        },
        {
          "member_id": "9",
          "primary_member": "no",
          "under_id": "3",
          "relative_id": "730419",
          "relation": "Daughter",
          "name": "Rani",
          "moblie_no": "9658965895",
          "email": "rani@gmail.com",
          "profession": "Dance",
          "age": "23",
          "d_o_b": "2001-02-13",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/1.png",
          "address": "4th Floor, 62, Prashant Building, Janmabhoomi Marg, Fort",
          "created_at": "2025-07-14 08:12:07",
          "status": "1",
        },
        {
          "member_id": "10",
          "primary_member": "no",
          "under_id": "5",
          "relative_id": "730419",
          "relation": "Sun",
          "name": "Vishal",
          "moblie_no": "7485859696",
          "email": "vishal@gmil.com",
          "profession": "IT",
          "age": "26",
          "d_o_b": "2025-07-01",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/3.png",
          "address": "Shop No 1, Vaidya Bldg, Veer Savarkar Path, Opp St Jhon High School, Thane (west)",
          "created_at": "2025-07-14 08:15:19",
          "status": "1",
        },
        {
          "member_id": "11",
          "primary_member": "no",
          "under_id": "5",
          "relative_id": "730419",
          "relation": "Daughter",
          "name": "Suman",
          "moblie_no": "9978457898",
          "email": "suman@gmail.com",
          "profession": "Shinging",
          "age": "12",
          "d_o_b": "2005-03-02",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/2.png",
          "address": "Shop No 1, Vaidya Bldg, Veer Savarkar Path, Opp St Jhon High School, Thane (west)",
          "created_at": "2025-07-14 08:17:09",
          "status": "1",
        },
        {
          "member_id": "12",
          "primary_member": "no",
          "under_id": "2",
          "relative_id": "730419",
          "relation": "Daughter",
          "name": "Suraj",
          "moblie_no": "9658969998",
          "email": "suraj@gmail.com",
          "profession": "Actor",
          "age": "24",
          "d_o_b": "2004-06-02",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/1752481951_3.jpg",
          "address": "4th Floor, 62, Prashant Building, Janmabhoomi Marg, Fort",
          "created_at": "2025-07-14 08:20:45",
          "status": "1",
        },
        {
          "member_id": "13",
          "primary_member": "no",
          "under_id": "2",
          "relative_id": "730419",
          "relation": "Daughter",
          "name": "Champa",
          "moblie_no": "74125487878",
          "email": "chapm@gmail.com",
          "profession": "Study",
          "age": "12",
          "d_o_b": "2222-02-02",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/1.png",
          "address": "4th Floor, 62, Prashant Building, Janmabhoomi Marg, Fort",
          "created_at": "2025-07-14 08:30:31",
          "status": "1",
        },
        {
          "member_id": "14",
          "primary_member": "no",
          "under_id": "2",
          "relative_id": "730419",
          "relation": "Sun",
          "name": "Dinesh",
          "moblie_no": "7256898989",
          "email": "dinesh@gmail.com",
          "profession": "Web Designer",
          "age": "26",
          "d_o_b": "2000-02-02",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/4.jpg",
          "address": "4th Floor, 62, Prashant Building, Janmabhoomi Marg, Fort",
          "created_at": "2025-07-14 08:31:35",
          "status": "1",
        },
        {
          "member_id": "15",
          "primary_member": "yes",
          "under_id": "0",
          "relative_id": "508487",
          "relation": "",
          "name": "Rajesh",
          "moblie_no": "8888888888",
          "email": "rajesh@gmail.com",
          "profession": "Driver",
          "age": "55",
          "d_o_b": "2000-02-01",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/13.png",
          "address": "A 14 1 Flr, Silverline Co Op Soc, D G Market, Near Ranjan, Bhayander (w)",
          "created_at": "2025-07-14 09:43:12",
          "status": "1",
        },
        {
          "member_id": "16",
          "primary_member": "yes",
          "under_id": "0",
          "relative_id": "744643",
          "relation": "",
          "name": "kailash",
          "moblie_no": "9627407876",
          "email": "kailash210111@gmail.com",
          "profession": "JOB",
          "age": "30",
          "d_o_b": "2025-07-14",
          "profile_img":
              "https://staging.infowebsoftware.com/FamilyTree/uploads/WhatsApp_Image_2025-07-13_at_10.12.10_38819320-removebg-preview.png",
          "address": "Haldwani Rampur Road, Uttarakhand",
          "created_at": "2025-07-14 09:48:45",
          "status": "1",
        },
        {
          "member_id": "17",
          "primary_member": "no",
          "under_id": "16",
          "relative_id": "744643",
          "relation": "Son",
          "name": "Yash",
          "moblie_no": "9898989898",
          "email": "kailash210111@gmail.com",
          "profession": "Job",
          "age": "1",
          "d_o_b": "2025-07-14",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/download.png",
          "address": "Lalkuan Nainital uttarakhand India",
          "created_at": "2025-07-14 09:50:36",
          "status": "1",
        },
        {
          "member_id": "18",
          "primary_member": "no",
          "under_id": "2",
          "relative_id": "730419",
          "relation": "Daughter",
          "name": "Raj",
          "moblie_no": "799999999",
          "email": "raj@gmail.com",
          "profession": "Tv",
          "age": "55",
          "d_o_b": "2025-07-14",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/11.png",
          "address": "Testing",
          "created_at": "2025-07-14 11:59:17",
          "status": "1",
        },
        {
          "member_id": "19",
          "primary_member": "no",
          "under_id": "2",
          "relative_id": "730419",
          "relation": "Sun",
          "name": "Sumit",
          "moblie_no": "9686598698",
          "email": "sumit@gmail.com",
          "profession": "Race",
          "age": "42",
          "d_o_b": "2025-07-14",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/18.png",
          "address": "Testing",
          "created_at": "2025-07-14 12:00:00",
          "status": "1",
        },
        {
          "member_id": "20",
          "primary_member": "no",
          "under_id": "2",
          "relative_id": "730419",
          "relation": "Daughter",
          "name": "Sofiya",
          "moblie_no": "6859696996",
          "email": "sofiya@gmail.com",
          "profession": "Stodent",
          "age": "16",
          "d_o_b": "2025-07-14",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/14.png",
          "address": "Testing",
          "created_at": "2025-07-14 12:01:12",
          "status": "1",
        },
        {
          "member_id": "22",
          "primary_member": "no",
          "under_id": "16",
          "relative_id": "744643",
          "relation": "Daughter",
          "name": "kayra",
          "moblie_no": "8562359669",
          "email": "kayra@gmail.com",
          "profession": "Riding",
          "age": "15",
          "d_o_b": "2002-09-02",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/dammy.jpg",
          "address": "Twsting",
          "created_at": "2025-07-21 12:26:15",
          "status": "1",
        },
      ],
    };
    return MemberListModel.fromJson(responseData);
  }

  @override
  Future<MemberListModel> searchMemberList(String query) async {
    // Simulate a delay to mimic network latency
    await Future.delayed(const Duration(seconds: 2));
    // Mock response data
    dynamic responseData = {
      "status": true,
      "data": [
        {
          "member_id": "3",
          "primary_member": "no",
          "under_id": "2",
          "relative_id": "2",
          "relation": "Sun",
          "name": "Ram",
          "moblie_no": "7896541236",
          "email": "ram@gmail.com",
          "profession": "Devlaper",
          "age": "30",
          "d_o_b": "2025-07-12",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/profile.png",
          "address": "112, Doshi Chamber, Poona Sholapur Street Cor, Masjid Bunder (east)",
          "created_at": "2025-07-12 11:42:35",
          "status": "1",
        },
        {
          "member_id": "8",
          "primary_member": "no",
          "under_id": "3",
          "relative_id": "730419",
          "relation": "Sun",
          "name": "Ramgopal",
          "moblie_no": "8569856989",
          "email": "ramgopal@gmail.com",
          "profession": "Docter",
          "age": "22",
          "d_o_b": "2000-06-20",
          "profile_img": "https://staging.infowebsoftware.com/FamilyTree/uploads/3.png",
          "address": "Nr Maninagar Police Station, Maninagar",
          "created_at": "2025-07-14 08:02:37",
          "status": "1",
        },
      ],
    };
    return MemberListModel.fromJson(responseData);
  }
}
